setwd("C:/Users/avon/Documents/R/ndc")
library("RSelenium")
checkForServer()
startServer()
#startServer(args = c("-Dwebdriver.chrome.driver=C:/chromedriver"), log = FALSE, invisible = FALSE)
#remDr <- remoteDriver$new()
remDr <- remoteDriver(browserName = "chrome")
remDr$open()
remDr$navigate("https://www.google.co.in/trends/")
webElmem1 <- remDr$findElement("class name", "ng-pristine")
webElmem1$sendKeysToElement(list('twitter', key = 'enter'))
webElmem2 <- remDr$findElement("class", "more-vert")
webElmem2$clickElement()
webElmem3 <- remDr$findElement("class", "csv-image")
webElmem3$clickElement()
